/* This file is auto-generated by SST. Do not edit. */
/* tslint:disable */
/* eslint-disable */
import "sst";
export {};
declare module "sst" {
  export interface Resource {
    LastFmApiKey: {
      type: "sst.sst.Secret";
      value: string;
    };
    PortfolioApp: {
      type: "sst.aws.Nextjs";
      url: string;
    };
  }
}
