import { Separator } from "@/components/ui/separator";
import { NextIntlClientProvider } from "next-intl";
// import type { Metadata } from "next";

// export const metadata: Metadata = {
//   title: "Create Next App",
//   description: "Generated by create next app",
// };

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <div className="flex min-h-screen flex-col items-center justify-center gap-4">
      <NextIntlClientProvider>{children}</NextIntlClientProvider>
      <footer className="text-center text-xs min-w-36">
        <Separator />
        <p className="mt-4">
          トーマス＠
          <a href="https://uchuu.io" className="hover:underline">
            宇宙
          </a>
        </p>
      </footer>
    </div>
  );
}
